config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "chatroom#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  post "message", to: "messages#create"

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  # show last 20 messages only
  scope :custom_dispaly, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 15 }
  validates_uniqueness_of :username
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_dispaly
    @users = User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    # create a new message based on private method, save it, redirect to root path
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel', message: message_render(message)
    end
  end

  private

  # get the value of the message body from param
  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    # rendering partial from controller
    # here we are rendering views/messages/_message.html.erb partial
    # as the partial also requires message object, passing it using locals method.
    render(partial: 'message', locals: { message: message })
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :log_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to root_path
    else
      # rendering new form again
      flash.now[:error] = "Can't login, credentials not matching"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out successfully"
    redirect_to login_path
  end

  private

  def log_in_redirect
    if logged_in?
      # example: if user is already logged in, then they are not supposed to see login path
      flash[:error] = "Your are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular coffee orange icon"></i>
  Friends
</h2>

<div class="ui grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message_container">
          <!-- as we are passing @messages to render, it expects partial with structure of views/messages/_message.html.erb  -->
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: "ui reply form", role: "form" }, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, id: "message_body", placeholder: current_user.username %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical pointing menu">
          <a class="item active">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui large inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item" %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to "Log out", logout_path, method: :delete, class: "item" %>
          <% else %>
            <%= link_to "Log In", login_path, class: "item" %>
            <a class="item">Sign up</a>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <%= link_to "Log in", login_path, class: "ui primary button" %>
        </div>
      <% else %>
        <div class="item">
          <span><em><%= current_user.username %></em></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageMe</title>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render "layouts/navigation" %>
<div class="ui container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

</body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>:<%= message.body %>
    </div>
  </div>
</div>